import type { Theme } from './types'

export const githubDark: Theme = {
  name: 'GitHub Dark',
  syntax: {
    attribute: { fg: '#79c0ff' },
    boolean: { fg: '#79c0ff' },
    comment: { fg: '#8b949e', italic: true },
    constant: { fg: '#79c0ff' },
    constructor: { fg: '#d2a8ff' },
    embedded: { fg: '#e6edf3' },
    error: { fg: '#f85149' },
    escape: { fg: '#79c0ff' },
    function: { fg: '#d2a8ff' },
    keyword: { fg: '#ff7b72' },
    'keyword.operator': { fg: '#ff7b72' },
    label: { fg: '#ff7b72' },
    'markup.heading': { bold: true, fg: '#79c0ff' },
    'markup.italic': { fg: '#e6edf3', italic: true },
    'markup.link': { fg: '#a5d6ff' },
    'markup.link.label': { fg: '#79c0ff' },
    'markup.link.url': { fg: '#a5d6ff', underline: true },
    'markup.list': { fg: '#ff7b72' },
    'markup.quote': { fg: '#8b949e', italic: true },
    'markup.raw': { fg: '#a5d6ff' },
    'markup.strong': { bold: true, fg: '#e6edf3' },
    namespace: { fg: '#79c0ff' },
    number: { fg: '#79c0ff' },
    operator: { fg: '#ff7b72' },
    property: { fg: '#79c0ff' },
    punctuation: { fg: '#8b949e' },
    'punctuation.special': { fg: '#79c0ff' },
    string: { fg: '#a5d6ff' },
    tag: { fg: '#7ee787' },
    type: { fg: '#ff7b72' },
    variable: { fg: '#ffa657' },
    'variable.builtin': { fg: '#79c0ff' },
    'variable.member': { fg: '#e6edf3' },
  },
  ui: {
    accent: '#58a6ff',
    activeTabFg: '#e6edf3',
    barBg: '#010409',
    bg: '#0d1117',
    currentLine: '#161b22',
    cursor: '#e6edf3',
    dim: '#8b949e',
    dirty: '#d29922',
    error: '#f85149',
    faint: '#6e7681',
    folder: '#e6edf3',
    gitAdded: '#3fb950',
    gitDeleted: '#f85149',
    gitModified: '#d29922',
    gutter: '#484f58',
    inactiveTabFg: '#8b949e',
    indentGuide: '#1a1e24',
    panelBg: '#161b22',
    scrollbar: '#484f58',
    statusBg: '#1f6feb',
    statusFg: '#ffffff',
    text: '#e6edf3',
    treeFocusBg: '#21262d',
    treeSelectedBg: '#193356',
  },
}
