import type { Theme } from './types'

export const githubDark: Theme = {
  name: 'GitHub Dark',
  ui: {
    bg: '#0d1117',
    panelBg: '#161b22',
    barBg: '#010409',
    statusBg: '#1f6feb',
    statusFg: '#ffffff',
    text: '#e6edf3',
    dim: '#8b949e',
    faint: '#6e7681',
    accent: '#58a6ff',
    activeTabFg: '#e6edf3',
    inactiveTabFg: '#8b949e',
    treeSelectedBg: '#193356',
    treeFocusBg: '#21262d',
    dirty: '#d29922',
    error: '#f85149',
    folder: '#e6edf3',
    cursor: '#e6edf3',
    scrollbar: '#484f58',
    gutter: '#484f58',
    currentLine: '#161b22',
    indentGuide: '#1a1e24',
    gitAdded: '#3fb950',
    gitModified: '#d29922',
    gitDeleted: '#f85149',
  },
  syntax: {
    'comment': { fg: '#8b949e', italic: true },
    'keyword': { fg: '#ff7b72' },
    'keyword.operator': { fg: '#ff7b72' },
    'operator': { fg: '#ff7b72' },
    'string': { fg: '#a5d6ff' },
    'escape': { fg: '#79c0ff' },
    'number': { fg: '#79c0ff' },
    'boolean': { fg: '#79c0ff' },
    'constant': { fg: '#79c0ff' },
    'function': { fg: '#d2a8ff' },
    'constructor': { fg: '#d2a8ff' },
    'type': { fg: '#ff7b72' },
    'namespace': { fg: '#79c0ff' },
    'variable': { fg: '#ffa657' },
    'variable.builtin': { fg: '#79c0ff' },
    'variable.member': { fg: '#e6edf3' },
    'property': { fg: '#79c0ff' },
    'attribute': { fg: '#79c0ff' },
    'tag': { fg: '#7ee787' },
    'label': { fg: '#ff7b72' },
    'punctuation': { fg: '#8b949e' },
    'punctuation.special': { fg: '#79c0ff' },
    'embedded': { fg: '#e6edf3' },
    'error': { fg: '#f85149' },
    'markup.heading': { fg: '#79c0ff', bold: true },
    'markup.strong': { fg: '#e6edf3', bold: true },
    'markup.italic': { fg: '#e6edf3', italic: true },
    'markup.raw': { fg: '#a5d6ff' },
    'markup.link': { fg: '#a5d6ff' },
    'markup.link.label': { fg: '#79c0ff' },
    'markup.link.url': { fg: '#a5d6ff', underline: true },
    'markup.list': { fg: '#ff7b72' },
    'markup.quote': { fg: '#8b949e', italic: true },
  },
}
