import { createHash } from 'node:crypto'
import { chmod, cp, mkdir, rm } from 'node:fs/promises'

// Only the *outputs* move with DRUK_DIST, so a test run never rewrites the dist/ just built.
const DIST = process.env.DRUK_DIST ?? './dist'
const RELEASE_DIR = `${DIST}/release`
const BOTTLE_STAGE = `${DIST}/bottle`

const { version, description, homepage, license } =
  await Bun.file('./package.json').json()

const ARCHIVES = {
  'darwin-arm64': 'druk-darwin-arm64.zip',
  'darwin-x64': 'druk-darwin-x64.zip',
  'linux-arm64': 'druk-linux-arm64.tar.gz',
  'linux-x64': 'druk-linux-x64.tar.gz',
} as const

// The *oldest* system each binary runs on; brew pours the newest bottle at or below the host.
const BOTTLE_TAGS = {
  'darwin-arm64': 'arm64_ventura',
  'darwin-x64': 'ventura',
  'linux-arm64': 'arm64_linux',
  'linux-x64': 'x86_64_linux',
} as const

type Target = keyof typeof ARCHIVES

async function sha256(path: string): Promise<string> {
  const file = Bun.file(path)
  if (!(await file.exists())) {
    process.stderr.write(
      `missing archive: ${path} — run \`bun run release\` first\n`
    )
    process.exit(1)
  }
  return createHash('sha256')
    .update(new Uint8Array(await file.arrayBuffer()))
    .digest('hex')
}

// Brew derives the bottle URL as `<name>-<version>.<tag>.bottle.tar.gz` — one dash, not two.
const bottleName = (tag: string) => `druk-${version}.${tag}.bottle.tar.gz`

async function bottle(target: Target, tag: string): Promise<string> {
  const binary = `${DIST}/${target}/druk`
  if (!(await Bun.file(binary).exists())) {
    process.stderr.write(
      `missing binary: ${binary} — run \`bun run build ${target}\` first\n`
    )
    process.exit(1)
  }

  const stage = `${BOTTLE_STAGE}/${tag}`
  await rm(stage, { force: true, recursive: true })
  await mkdir(`${stage}/druk/${version}/bin`, { recursive: true })
  await cp(binary, `${stage}/druk/${version}/bin/druk`)
  // The workflow downloads the binaries as artifacts, which do not carry a mode.
  await chmod(`${stage}/druk/${version}/bin/druk`, 0o755)

  const path = `${RELEASE_DIR}/${bottleName(tag)}`
  // Without COPYFILE_DISABLE macOS tar writes ._ AppleDouble members into the keg.
  await Bun.$`tar -czf ${path} -C ${stage} druk`.env({
    ...process.env,
    COPYFILE_DISABLE: '1',
  })
  return path
}

const targets = Object.keys(ARCHIVES) as Target[]

const sums = Object.fromEntries(
  await Promise.all(
    targets.map(async (target) => [
      target,
      await sha256(`${RELEASE_DIR}/${ARCHIVES[target]}`),
    ])
  )
) as Record<Target, string>

const bottles = Object.fromEntries(
  await Promise.all(
    targets.map(async (target) => [
      target,
      await sha256(await bottle(target, BOTTLE_TAGS[target])),
    ])
  )
) as Record<Target, string>

await rm(BOTTLE_STAGE, { force: true, recursive: true })

const base = `${homepage}/releases/download/v${version}`

// `brew audit --strict` fails a desc that opens with an article, and package.json's does.
const desc = description
  .replaceAll('"', "'")
  .split('—')[0]!
  .trim()
  .replace(/^(a|an|the) /iu, '')
  .replace(/^./u, (c: string) => c.toUpperCase())

// `any_skip_relocation`: a cellar path naming this machine's prefix sends everyone else to source.
const sha256s = targets
  .map(
    (target) =>
      `    sha256 cellar: :any_skip_relocation, ${BOTTLE_TAGS[target]}: "${bottles[target]}"`
  )
  .join('\n')

// Keep `version`: brew scans the archive stem, and `druk-darwin-arm64` ends in digits (stable 64).
const formula = `# Generated by scripts/formula.ts — do not edit by hand.
class Druk < Formula
  desc "${desc}"
  homepage "${homepage}"
  version "${version}"
  license "${license}"

  on_macos do
    on_arm do
      url "${base}/${ARCHIVES['darwin-arm64']}"
      sha256 "${sums['darwin-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['darwin-x64']}"
      sha256 "${sums['darwin-x64']}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${ARCHIVES['linux-arm64']}"
      sha256 "${sums['linux-arm64']}"
    end
    on_intel do
      url "${base}/${ARCHIVES['linux-x64']}"
      sha256 "${sums['linux-x64']}"
    end
  end

  bottle do
    root_url "${base}"
${sha256s}
  end

  def install
    bin.install "druk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/druk --version")
  end
end
`

await Bun.write(`${RELEASE_DIR}/druk.rb`, formula)
process.stdout.write(`wrote ${RELEASE_DIR}/druk.rb\n`)
